### PR TITLE
Added lifecycle policy

### PR DESCRIPTION
**Pull request by laurentb4**
ND-283 Added lifecycle policy to expire old untagged images and keep the latest 15 images.

### CODE REVIEW

**Comment by laurentb4** [comment]
Disabled transition from dev to pre-prod for pipeline to test policy effects in Dev first.

**Review by jamesgreen-moj — APPROVED** [review]
LGTM

**Review by smjmoj — APPROVED** [review]
LGTM

**Comment by asifamirat00** [comment]
approved

**Pull request merged**
